allprojects {
    apply plugin: "eclipse"

    version = '1.0'
    ext {
        appName = "My GDX Game"
        gdxVersion = '1.14.0'
        javaVersion = project.findProperty('javaVersion') ?: '17'
    }

    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
        maven { url = "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url = "https://oss.sonatype.org/content/repositories/releases/" }
        maven { url = "https://jitpack.io" }
    }
}

project(":desktop") {
    apply plugin: "java-library"

    dependencies {
        implementation project(":core")
        api "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
        api "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    }
}

project(":core") {
    apply plugin: "java-library"

    dependencies {
        api "com.badlogicgames.gdx:gdx:$gdxVersion"
    }
}
