buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath "org.docstr.gwt:org.docstr.gwt.gradle.plugin:$gwtPluginVersion"
    }
}

apply plugin: "org.docstr.gwt"
apply plugin: "war"

def outputPath = "build/dist/"

gwt {
    gwtVersion = "$gwtFrameworkVersion"
    maxHeapSize = '1G'
    minHeapSize = '1G'

    extraSourceDirs = files(
        file('src/'),
        files(project(':core').sourceSets.main.allJava.srcDirs),
    )
    modules = ["com.mygdx.game.GwtDefinition"]

    war = file(outputPath)
    compiler.optimize = 9
    compiler.strict = true

    sourceLevel = '11'

    devMode {
        port = 8080
        startupUrl = "http://127.0.0.1:8080/index.html"
    }
    superDev {
        modules = ["com.mygdx.game.GwtDefinitionSuperdev"]
    }
}

sourceCompatibility = 11
targetCompatibility = 11
sourceSets.main.java.srcDirs = ["src/"]

clean.delete += [file("war")]

tasks.named("compileJava").get().dependsOn("clean")

tasks.register('dist') {
    dependsOn(["build"])
    doLast {
        file(outputPath).mkdirs()
        copy {
            from("build/gwt/out") {
                exclude '**/*.symbolMap'
            }
            into outputPath
        }
        copy {
            from("webapp") {
                exclude 'index.html'
                exclude 'refresh.png'
            }
            into outputPath
        }
        copy {
            from("webapp") {
                include 'index.html'
                filter { String line -> line.replaceAll('<a class="superdev" .+</a>', '') }
            }
            into outputPath
        }
    }
}

tasks.register('superDev') {
    dependsOn('gwt-compiler')
    doLast {
        println "SuperDev mode ready. Open http://localhost:8080/index.html"
    }
}

eclipse.project.name = appName + "-html"
